version: "3.7"

services:
  nuclio:
    container_name: nuclio
    hostname: nuclio
    image: quay.io/nuclio/dashboard:stable-amd64
    restart: unless-stopped
    ports:
       - 8070:8070 # web ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock